### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by valeskini**
Added MY fork :P

### CODE REVIEW

**Comment by wilhelmy** [comment]
Nice! This Trias API is used in Graz, possibly in other cities as well. I tried to get it working years ago but abandoned the plan.

**Comment by wilhelmy** [comment]
Nvm, seems like everyone else uses MDV or HACON; https://www.offene-oeffis.at/status/

**Comment by valeskini** [comment]
The Verbund Linie TRIAS API should work in whole Styria including Graz. Im still working on implementing some of the smaller features for the Monitor but the base features are working as intended.

**Comment by valeskini** [comment]
And there is a MDV Endpoint for the verbundlinie but it seems like it isnt supported nor intended to be used by people like me. Sadly, verbundlinie only offers the most basic endpoints from TRIAS...

**Comment by wilhelmy** [comment]
Thanks for explaining and cool stuff. I might deploy it in Graz some time.
Normally, I would now merge the PR, but I no longer can so you're at the mercy of the new owners of the repository. :)

**Comment by valeskini** [comment]
I got the traffic infos working yesterday. Sadly it has to pull the html from their website because there is no official API for the traffic thingys but its working :#

**Comment by deadda7a** [comment]
:)

**Pull request merged**
